services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aggregation
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - './server_data/postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d aggregation" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    restart: unless-stopped
    depends_on:
      - postgres

  subscriptions:
      build:
        dockerfile: Dockerfile
      container_name: subscriptions
      ports:
        - 11682:11682
      env_file:
        - .env
      restart: unless-stopped
      depends_on:
        postgres:
          condition: service_healthy

volumes:
  postgres_data:
  subscriptions:
